
export const ANALYTICS_CREATE = 'ANALYTICS_CREATE';
export const IMPORT_PARAMS_FROM_GRAPH = 'IMPORT_PARAMS_FROM_GRAPH';
export const ANALYTICS_RUN = 'ANALYTICS_RUN';
export const ANALYTICS_ADD_VARIABLE = 'ANALYTICS_ADD_VARIABLE';
export const ANALYTICS_LM_DEPENDENT = 'ANALYTICS_LM_DEPENDENT';
export const ANALYTICS_LM_REGRESSOR = 'ANALYTICS_LM_REGRESSOR';
export const ANALYTICS_LM_GRAPHS = 'ANALYTICS_LM_GRAPHS';
export const ANALYTICS_ADD_VARIABLE_TO_LIST = 'ANALYTICS_ADD_VARIABLE_TO_LIST';

export const ANALYTICS_FILTER_GRAPH = 'ANALYTICS_FILTER_GRAPH';
export const ANALYTICS_UPDATE_PARAMETERS = 'ANALYTICS_UPDATE_PARAMETERS';

// store actions
export const ANALYTICS_SAVE_NEW = 'ANALYTICS_SAVE_NEW';
export const ANALYTICS_SAVE_STATUS = 'ANALYTICS_SAVE_STATUS';
export const ANALYTICS_SAVE_PARAMETERS = 'ANALYTICS_SAVE_PARAMETERS';
export const ANALYTICS_SAVE_RESOLVED_PARAMETERS = 'ANALYTICS_SAVE_RESOLVED_PARAMETERS';
export const ANALYTICS_SAVE_RESULTS = 'ANALYTICS_SAVE_RESULTS';
export const ANALYTICS_SAVE_UI = 'ANALYTICS_SAVE_UI';
export const ANALYTICS_SAVE_RESTORE_ANALYTICS = 'ANALYTICS_SAVE_RESTORE_ANALYTICS';

// delete analytics objects
export const DELETE_ANALYTICS_OBJECT = 'DELETE_ANALYTICS_OBJECT';
