export const ANALYTICS_LM_DEPENDENT = "ANALYTICS_LM_DEPENDENT";
export const ANALYTICS_LM_REGRESSOR = "ANALYTICS_LM_REGRESSOR";
export const ANALYTICS_LM_GRAPHS = "ANALYTICS_LM_GRAPHS";
export const ANALYTICS_ADD_VARIABLE_TO_LIST = "ANALYTICS_ADD_VARIABLE_TO_LIST";

export const ANALYTICS_FILTER_GRAPH = "ANALYTICS_FILTER_GRAPH";
