export const API_SET_JWT = 'API_SET_JWT_TYPE';
export const API_SET_PARAMETERS = 'API_SET_PARAMETERS';

// Observations
export const GRAPH_VIEWER_FETCH_GRAPH = 'GRAPH_VIEWER_FETCH_GRAPH';
export const GRAPH_VIEWER_INITIATE = 'GRAPH_VIEWER_INITIATE';
