/**
 * ChronosDB swagger
 * ChronosDB time series database API
 *
 * OpenAPI spec version: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Reference to observation in an annotation
*/
export class AnnotationTargetRequest {
    'tsid'?: string;
    /**
    * index
    */
    'index'?: number;
    'vid'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tsid",
            "baseName": "tsid",
            "type": "string",
            "format": ""
        },
        {
            "name": "index",
            "baseName": "index",
            "type": "number",
            "format": ""
        },
        {
            "name": "vid",
            "baseName": "vid",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AnnotationTargetRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

