/**
 * ChronosDB swagger
 * ChronosDB time series database API
 *
 * OpenAPI spec version: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ObjectType } from '../models/ObjectType';
import { HttpFile } from '../http/http';

export class PolicyUpdateObject {
    'type': ObjectType;
    'spaceId'?: string;
    'collId'?: string;
    'tsid'?: string;
    'subobject': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ObjectType",
            "format": ""
        },
        {
            "name": "spaceId",
            "baseName": "space_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "collId",
            "baseName": "coll_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "tsid",
            "baseName": "tsid",
            "type": "string",
            "format": ""
        },
        {
            "name": "subobject",
            "baseName": "subobject",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PolicyUpdateObject.attributeTypeMap;
    }

    public constructor() {
    }
}



