/**
 * ChronosDB swagger
 * ChronosDB time series database API
 *
 * OpenAPI spec version: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Action } from '../models/Action';
import { Effect } from '../models/Effect';
import { PolicyUpdateObject } from '../models/PolicyUpdateObject';
import { PolicyUpdateSubject } from '../models/PolicyUpdateSubject';
import { HttpFile } from '../http/http';

export class PolicyUpdate {
    'subject': PolicyUpdateSubject;
    'object': PolicyUpdateObject;
    'action': Action;
    'effect': Effect;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "subject",
            "baseName": "subject",
            "type": "PolicyUpdateSubject",
            "format": ""
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "PolicyUpdateObject",
            "format": ""
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "Action",
            "format": ""
        },
        {
            "name": "effect",
            "baseName": "effect",
            "type": "Effect",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PolicyUpdate.attributeTypeMap;
    }

    public constructor() {
    }
}



