/**
 * ChronosDB swagger
 * ChronosDB time series database API
 *
 * OpenAPI spec version: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RawSingleTimeSeriesData } from '../models/RawSingleTimeSeriesData';
import { VintageUpdate } from '../models/VintageUpdate';
import { HttpFile } from '../http/http';

export class RawDataPutRequest {
    'series'?: Array<RawSingleTimeSeriesData>;
    'vintage'?: VintageUpdate;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "series",
            "baseName": "series",
            "type": "Array<RawSingleTimeSeriesData>",
            "format": ""
        },
        {
            "name": "vintage",
            "baseName": "vintage",
            "type": "VintageUpdate",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RawDataPutRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

