/**
 * ChronosDB swagger
 * ChronosDB time series database API
 *
 * OpenAPI spec version: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RawDataPutResponseSeriesInner } from '../models/RawDataPutResponseSeriesInner';
import { VintageSummary } from '../models/VintageSummary';
import { HttpFile } from '../http/http';

/**
* Successful data write for a list of series
*/
export class RawDataPutResponse {
    'series'?: Array<RawDataPutResponseSeriesInner>;
    'vintage'?: VintageSummary;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "series",
            "baseName": "series",
            "type": "Array<RawDataPutResponseSeriesInner>",
            "format": ""
        },
        {
            "name": "vintage",
            "baseName": "vintage",
            "type": "VintageSummary",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RawDataPutResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

