/**
 * ChronosDB swagger
 * ChronosDB time series database API
 *
 * OpenAPI spec version: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SpaceMemberPost {
    /**
    * member type: `g` group `u` user 
    */
    'type'?: SpaceMemberPostTypeEnum;
    'id'?: string;
    /**
    * member role: `annotator` space member, who can annotate data `uploader` space member, who can write data `analyst` space member, who can read/write data, read members `maintainer` space maintainer, who can add/remove members, and edit space info `owner` space owner, who can transfer ownership and delete the space 
    */
    'role'?: SpaceMemberPostRoleEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "SpaceMemberPostTypeEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "SpaceMemberPostRoleEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SpaceMemberPost.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum SpaceMemberPostTypeEnum {
    G = 'g',
    U = 'u'
}
export enum SpaceMemberPostRoleEnum {
    Annotator = 'annotator',
    Uploader = 'uploader',
    Analyst = 'analyst',
    Maintainer = 'maintainer',
    Owner = 'owner'
}

