/**
 * ChronosDB swagger
 * ChronosDB time series database API
 *
 * OpenAPI spec version: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GroupSummary } from '../models/GroupSummary';
import { SubjectType } from '../models/SubjectType';
import { UserSummary } from '../models/UserSummary';
import { HttpFile } from '../http/http';

export class Subject {
    'type': SubjectType;
    'user'?: UserSummary;
    'group'?: GroupSummary;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "SubjectType",
            "format": ""
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "UserSummary",
            "format": ""
        },
        {
            "name": "group",
            "baseName": "group",
            "type": "GroupSummary",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Subject.attributeTypeMap;
    }

    public constructor() {
    }
}



