/**
 * FRED API
 * API for accessing economic data from the Federal Reserve Economic Data (FRED) database.
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ObservationsObservationsInner } from '../models/ObservationsObservationsInner';
import { HttpFile } from '../http/http';

export class Observations {
    'realtimeStart'?: string;
    'realtimeEnd'?: string;
    'observationStart'?: string;
    'observationEnd'?: string;
    'units'?: string;
    'outputType'?: number;
    'fileType'?: string;
    'orderBy'?: string;
    'sortOrder'?: string;
    'count'?: number;
    'offset'?: number;
    'limit'?: number;
    'observations'?: Array<ObservationsObservationsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "realtimeStart",
            "baseName": "realtime_start",
            "type": "string",
            "format": "date"
        },
        {
            "name": "realtimeEnd",
            "baseName": "realtime_end",
            "type": "string",
            "format": "date"
        },
        {
            "name": "observationStart",
            "baseName": "observation_start",
            "type": "string",
            "format": ""
        },
        {
            "name": "observationEnd",
            "baseName": "observation_end",
            "type": "string",
            "format": ""
        },
        {
            "name": "units",
            "baseName": "units",
            "type": "string",
            "format": ""
        },
        {
            "name": "outputType",
            "baseName": "output_type",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "fileType",
            "baseName": "file_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "orderBy",
            "baseName": "order_by",
            "type": "string",
            "format": ""
        },
        {
            "name": "sortOrder",
            "baseName": "sort_order",
            "type": "string",
            "format": ""
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "offset",
            "baseName": "offset",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "observations",
            "baseName": "observations",
            "type": "Array<ObservationsObservationsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Observations.attributeTypeMap;
    }

    public constructor() {
    }
}

