/**
 * FRED API
 * API for accessing economic data from the Federal Reserve Economic Data (FRED) database.
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SourcesSourcesInner } from '../models/SourcesSourcesInner';
import { HttpFile } from '../http/http';

export class Sources {
    'realtimeStart'?: string;
    'realtimeEnd'?: string;
    'sources'?: Array<SourcesSourcesInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "realtimeStart",
            "baseName": "realtime_start",
            "type": "string",
            "format": "date"
        },
        {
            "name": "realtimeEnd",
            "baseName": "realtime_end",
            "type": "string",
            "format": "date"
        },
        {
            "name": "sources",
            "baseName": "sources",
            "type": "Array<SourcesSourcesInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Sources.attributeTypeMap;
    }

    public constructor() {
    }
}

