/**
 * FRED API
 * API for accessing economic data from the Federal Reserve Economic Data (FRED) database.
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TagsTagsInner {
    'name'?: string;
    'groupId'?: string;
    'notes'?: string;
    'created'?: string;
    'popularity'?: number;
    'seriesCount'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "groupId",
            "baseName": "group_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "string",
            "format": ""
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "string",
            "format": ""
        },
        {
            "name": "popularity",
            "baseName": "popularity",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "seriesCount",
            "baseName": "series_count",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return TagsTagsInner.attributeTypeMap;
    }

    public constructor() {
    }
}

