export const API_SET_JWT = 'API_SET_JWT_TYPE';
export const API_SET_PARAMETERS = 'API_SET_PARAMETERS';
export const API_SAVE_PARAMETERS = 'API_SAVE_PARAMETERS';

// initialize viewer
export const INITIALIZE = 'INITIALIZE';

// reset store to initial state
export const STORE_RESET = 'STORE_RESET';

// DEFAULTS
export const DEFAULTS_SET = 'DEFAULTS_SET';
export const DEFAULTS_CLEAR = 'DEFAULTS_CLEAR';

// NAMESPACE
export const NAMESPACE_UPDATE = 'NAMESPACE_UPDATE';

// UI
export const TIMESERIES_BROWSER_SET_SPACES_LOADING = 'TIMESERIES_BROWSER_SET_SPACES_LOADING';
export const TIMESERIES_BROWSER_SET_TIMESERIES_LOADING = 'TIMESERIES_BROWSER_SET_TIMESERIES_LOADING';
export const TIMESERIES_BROWSER_SELECT_SPACE = 'TIMESERIES_BROWSER_SELECT_SPACE';
export const TIMESERIES_BROWSER_SELECT_COLLECTION = 'TIMESERIES_BROWSER_SELECT_COLLECTION';
export const TIMESERIES_BROWSER_EXPAND_SPACE = 'TIMESERIES_BROWSER_EXPAND_SPACE';
export const TIMESERIES_BROWSER_COLLAPSE_SPACE = 'TIMESERIES_BROWSER_COLLAPSE_SPACE';
export const TIMESERIES_BROWSER_SET_SPACE_LOADING = 'TIMESERIES_BROWSER_SET_SPACE_LOADING';
export const TIMESERIES_VIEWER_SELECT_TIMESERIES = 'TIMESERIES_VIEWER_SELECT_TIMESERIES';
export const TIMESERIES_VIEWER_SELECT_COLLECTION = 'TIMESERIES_VIEWER_SELECT_COLLECTION';
export const TIMESERIES_VIEWER_SET_FAILED_COLLECTIONS = 'TIMESERIES_VIEWER_SET_FAILED_COLLECTIONS';
export const TIMESERIES_BROWSER_SET_OVER_NODE_ID = 'TIMESERIES_BROWSER_SET_OVER_NODE_ID';
export const TIMESERIES_BROWSER_ADD_SERIES = 'TIMESERIES_BROWSER_ADD_SERIES';
export const TOGGLE_CREATE_SPACE_OVERLAY = 'TOGGLE_CREATE_SPACE_OVERLAY';
export const TOGGLE_CREATE_COLLECTION_OVERLAY = 'TOGGLE_CREATE_COLLECTION_OVERLAY';
export const TOGGLE_CREATE_TIMESERIES_OVERLAY = 'TOGGLE_CREATE_TIMESERIES_OVERLAY';
export const TOGGLE_DELETE_SPACE_COLLECTION_OVERLAY = 'TOGGLE_DELETE_SPACE_COLLECTION_OVERLAY';
export const ANNOTATIONS_TOGGLE_ANNOTATIONS_VISIBLE = 'ANNOTATIONS_TOGGLE_ANNOTATIONS_VISIBLE';
export const ANNOTATIONS_TOGGLE_ANNOTATIONS_EDIT_MODE = 'ANNOTATIONS_TOGGLE_ANNOTATIONS_EDIT_MODE';
export const ANNOTATIONS_SET_ANNOTATION_REQUEST_PENDING = 'ANNOTATIONS_SET_ANNOTATION_REQUEST_PENDING';
export const ANNOTATIONS_ANNOTATION_DELETE_REQUEST_SET_PENDING = 'ANNOTATIONS_ANNOTATION_DELETE_REQUEST_SET_PENDING';
export const ANNOTATIONS_SET_CREATE_DIALOG_VISIBILITY = 'ANNOTATIONS_SET_CREATE_DIALOG_VISIBILITY';
export const ANNOTATIONS_SET_ADD_TARGET_DIALOG_VISIBILITY = 'ANNOTATIONS_SET_ADD_TARGET_DIALOG_VISIBILITY';
export const ANNOTATIONS_SET_DELETE_DIALOG_VISIBILITY = 'ANNOTATIONS_SET_DELETE_DIALOG_VISIBILITY';
export const ANNOTATIONS_SET_ADD_TARGET = 'ANNOTATIONS_SET_ADD_TARGET';
export const ANNOTATIONS_SET_DELETE_TARGET = 'ANNOTATIONS_SET_DELETE_TARGET';
export const ANNOTATIONS_SET_ANNOTATION_LIST_VISIBILITY = 'ANNOTATIONS_SET_ANNOTATION_LIST_VISIBILITY';
export const FRED_BROWSER_SET_CATEGOTY_LOADING = 'FRED_BROWSER_SET_CATEGOTY_LOADING';
export const FRED_BROWSER_TOGGLE_CONFIG_OVERLAY = 'FRED_BROWSER_TOGGLE_CONFIG_OVERLAY';
export const FRED_BROWSER_SELECT_CATEGORY = 'FRED_BROWSER_SELECT_CATEGORY';
export const FRED_BROWSER_SET_CATEGORY_LOADING = 'FRED_BROWSER_SET_CATEGORY_LOADING';
export const FRED_BROWSER_SET_SERIES_LOADING = 'FRED_BROWSER_SET_SERIES_LOADING';
// ui triggered sagas
export const FRED_BROWSER_EXPAND_CATEGORY = 'FRED_BROWSER_EXPAND_CATEGORY';
export const FRED_BROWSER_COLLAPSE_CATEGORY = 'FRED_BROWSER_COLLAPSE_CATEGORY';
// listen to by reducer
export const FRED_BROWSER_SAVE_EXPANDED_CATEGORY = 'FRED_BROWSER_SAVE_EXPANDED_CATEGORY';
export const FRED_BROWSER_SAVE_COLLAPSED_CATEGORY = 'FRED_BROWSER_SAVE_COLLAPSED_CATEGORY';
export const FRED_BROWSER_SAVE_SELECT_CATEGORY = 'FRED_BROWSER_SAVE_SELECT_CATEGORY';

// Spaces
export const FETCH_SPACES = 'FETCH_SPACES';
export const DELETE_SPACE = 'DELETE_SPACE';
export const SAVE_SPACES = 'SAVE_SPACES';
export const SAVE_SPACE = 'SAVE_SPACE';
export const FETCH_SPACE_DETAILS = 'FETCH_SPACE_DETAILS';
export const SAVE_SPACE_DETAILS = 'SAVE_SPACE_DETAILS';
export const SAVE_SPACE_REMOVE = 'SAVE_SPACE_REMOVE';

// Collections
export const FETCH_COLLECTIONS = 'FETCH_COLLECTIONS';
export const REFETCH_COLLECTIONS = 'REFETCH_COLLECTIONS';
export const SAVE_COLLECTIONS = 'SAVE_COLLECTIONS';
export const SAVE_COLLECTION = 'SAVE_COLLECTION';
export const DELETE_COLLECTION = 'DELETE_COLLECTION';
export const FETCH_COLLECTION_DETAILS = 'FETCH_COLLECTION_DETAILS';
export const SAVE_COLLECTION_DETAILS = 'SAVE_COLLECTION_DETAILS';
export const SAVE_COLLECTION_REMOVE = 'SAVE_COLLECTION_REMOVE';

// Annotations
export const FETCH_ANNOTATIONS = 'FETCH_ANNOTATIONS';
export const SAVE_ANNOTATIONS = 'SAVE_ANNOTATIONS';
export const SAVE_SINGLE_ANNOTATION = 'SAVE_SINGLE_ANNOTATION';
export const CREATE_ANNOTATION = 'CREATE_ANNOTATION';
export const CREATE_ANNOTATION_SUCCESS = 'CREATE_ANNOTATION_SUCCESS';
export const DELETE_ANNOTATION = 'DELETE_ANNOTATION';
export const DELETE_ANNOTATION_SUCCESS = 'DELETE_ANNOTATION_SUCCESS';
export const SET_DELETE_DIALOG_STATUS = 'SET_DELETE_DIALOG_STATUS';
export const DELETE_ANNOTATION_TARGET_ACTION = 'DELETE_ANNOTATION_TARGET_ACTION';
export const SAVE_STATUS_OF_DELETE_ANNOTATION_TARGET = 'SAVE_STATUS_OF_DELETE_ANNOTATION_TARGET';
export const ADD_ANNOTATION_TARGET = 'ADD_ANNOTATION_TARGET';
export const ADD_ANNOTATION_TARGET_SUCCESS = 'ADD_ANNOTATION_TARGET_SUCCESS';
export const UPDATE_ANNOTATION_TEXT = 'UPDATE_ANNOTATION_TEXT';
export const UPDATE_ANNOTATION_SUCCESS = 'UPDATE_ANNOTATION_SUCCESS';
export const SAVE_STATUS_OF_UPDATING_ANNOTATION = 'SAVE_STATUS_OF_UPDATING_ANNOTATION';
export const SAVE_ANNOTATION_ERRORS = 'SAVE_ANNOTATION_ERRORS';

// Timeseries
export const FETCH_TIMESERIES = 'FETCH_TIMESERIES';
export const UPDATE_TIMESERIES = 'UPDATE_TIMESERIES';
export const FETCH_TIMESERIES_LIST = 'FETCH_TIMESERIES_LIST';
export const FETCH_TIMESERIES_DETAILS = 'FETCH_TIMESERIES_DETAILS';
export const TIMESERIES_DELETE_SERIES = 'TIMESERIES_DELETE_SERIES';

export const SAVE_TIMESERIES_DETAILS = 'SAVE_TIMESERIES_DETAILS';
export const SAVE_TIMESERIES_LIST = 'SAVE_TIMESERIES_LIST';
export const SAVE_TIMESERIES = 'SAVE_TIMESERIES';
export const SAVE_TIMESERIES_DELETE = 'SAVE_TIMESERIES_DELETE';

// Fred
export const FETCH_FRED_CATEGORY = 'FETCH_FRED_CATEGORY';
export const FETCH_FRED_CATEGORY_TIMESERIES = 'FETCH_FRED_CATEGORY_TIMESERIES';

export const SAVE_FRED_CATEGORY = 'SAVE_FRED_CATEGORY';
export const SAVE_FRED_TIMESERIES_LIST = 'SAVE_FRED_TIMESERIES_LIST';
export const SAVE_FRED_CONFIG = 'SAVE_FRED_CONFIG';

// Observations
export const FETCH_OBSERVATIONS = 'FETCH_OBSERVATIONS';
export const SAVE_OBSERVATIONS = 'FETCH_OBSERVATIONS';

// Graph
export const GRAPH_CREATE = 'GRAPH_CREATE';
export const CLONE_GRAPH = 'CLONE_GRAPH';
export const GRAPH_UPDATE = 'GRAPH_UPDATE'; // main process
export const GRAPH_FOCUS = 'GRAPH_FOCUS';
export const GRAPH_ADD_SERIES = 'GRAPH_ADD_SERIES';
export const GRAPH_ADD_EXPR_SERIES = 'GRAPH_ADD_EXPR_SERIES';
export const GRAPH_ADD_NAMED_SERIES = 'GRAPH_ADD_NAMED_SERIES';
export const GRAPH_ADD_REF_SERIES = 'GRAPH_ADD_REF_SERIES';
export const GRAPH_ADD_DATA_SERIES = 'GRAPH_ADD_DATA_SERIES';
export const GRAPH_ADD_MANY_REF_SERIES = 'GRAPH_ADD_MANY_REF_SERIES';
export const GRAPH_CLEAR_N_ADD_SERIES = 'GRAPH_CLEAR_N_ADD_SERIES';
// export const GRAPH_APPEND_SERIES = 'GRAPH_APPEND_SERIES';
export const GRAPH_REMOVE_SERIES = 'GRAPH_REMOVE_SERIES';
export const GRAPH_CLEAR_SERIES = 'GRAPH_CLEAR_SERIES';
export const GRAPH_UPDATE_SERIES_PROPS = 'GRAPH_UPDATE_SERIES_PROPS';
export const GRAPH_UPDATE_GRAPH_PROPS = 'GRAPH_UPDATE_GRAPH_PROPS';
export const GRAPH_UPDATE_UI_PROPS = 'GRAPH_UPDATE_UI_PROPS';
export const GRAPH_REORDER_SERIES = 'GRAPH_REORDER_SERIES';
export const GRAPH_SELECT_SERIES = 'GRAPH_SELECT_SERIES';
export const GRAPH_DESELECT_SERIES = 'GRAPH_DESELECT_SERIES';
export const GRAPH_DELETE_OBJECT = 'GRAPH_DELETE_OBJECT';

export const GRAPH_UPDATE_TITLE = 'GRAPH_UPDATE_TITLE';
export const GRAPH_UPDATE_REALTIME = 'GRAPH_UPDATE_REALTIME';
export const GRAPH_UPDATE_RANGE = 'GRAPH_UPDATE_RANGE';
export const GRAPH_APPLY_UNARY_FUNC = 'GRAPH_APPLY_UNARY_FUNC';
export const GRAPH_APPLY_BINARY_FUNC = 'GRAPH_APPLY_BINARY_FUNC';
export const GRAPH_APPLY_BINARY_OPERATOR = 'GRAPH_APPLY_BINARY_OPERATOR';
export const GRAPH_UPDATE_SERIES_EXPR = 'GRAPH_UPDATE_SERIES_EXPR';
export const GRAPH_CLONE_SERIES = 'GRAPH_CLONE_SERIES';
export const GRAPH_GRAPH_RESOLVE_ALL_SERIES = 'GRAPH_GRAPH_RESOLVE_ALL_SERIES';
export const GRAPH_EXPORT_LOCAL = 'GRAPH_EXPORT_LOCAL';

/*
  GRAPH_UPDATE_* actions are used to trigger sagas at different stage of graph processing
*/
// user GRAPH_UPDATE with a stage and wsid
export const GRAPH_UPDATE_OUTPUT = 'GRAPH_UPDATE_OUTPUT';
export const GRAPH_UPDATE_STATUS = 'GRAPH_UPDATE_STATUS';

/*
  GRAPH_ERRORS_* actions takes care of any errors during graph evaluation
*/
export const GRAPH_ERRORS_ADD = 'GRAPH_ERRORS_ADD';
export const GRAPH_ERRORS_CLEAR = 'GRAPH_ERRORS_CLEAR';

/*
  GRAPH_SAVE_* actions are used to interact with the store
*/
export const GRAPH_SAVE_NEW_GRAPH = 'GRAPH_SAVE_NEW_GRAPH';
export const GRAPH_SAVE_CURRENT_GID = 'GRAPH_SAVE_CURRENT_GID';
export const GRAPH_SAVE_GRAPH_OBJECT = 'GRAPH_SAVE_GRAPH_OBJECT';
export const GRAPH_SAVE_SERIES_DEF = 'GRAPH_SAVE_SERIES_DEF';
export const GRAPH_SAVE_DETERMINED_FREQ = 'GRAPH_SAVE_DETERMINED_FREQ';
export const GRAPH_SAVE_TRANSFORMED_SERIES = 'GRAPH_SAVE_TRANSFORMED_SERIES';
export const GRAPH_SAVE_TRANSFORMED_SERIES_BULK = 'GRAPH_SAVE_TRANSFORMED_SERIES_BULK';
export const GRAPH_SAVE_OUTPUT = 'GRAPH_SAVE_OUTPUT';
export const GRAPH_SAVE_APPEND_SERIES = 'GRAPH_SAVE_APPEND_SERIES';
export const GRAPH_SAVE_REMOVE_SERIES = 'GRAPH_SAVE_REMOVE_SERIES';
export const GRAPH_SAVE_CLEAR_SERIES = 'GRAPH_SAVE_CLEAR_SERIES';
export const GRAPH_SAVE_REORDER_SERIES = 'GRAPH_SAVE_REORDER_SERIES';
export const GRAPH_SAVE_GRAPH_PROPS = 'GRAPH_SAVE_GRAPH_PROPS';
export const GRAPH_SAVE_SERIES_PROPS = 'GRAPH_SAVE_SERIES_PROPS';
export const GRAPH_SAVE_UI_PROPS = 'GRAPH_SAVE_UI_PROPS';
export const GRAPH_SAVE_EXPORT_OPTIONS = 'GRAPH_SAVE_EXPORT_OPTIONS';
export const GRAPH_SAVE_REPLACE_SERIES = 'GRAPH_SAVE_REPLACE_SERIES';
export const GRAPH_SAVE_SELECT_SERIES = 'GRAPH_SAVE_SELECT_SERIES';
export const GRAPH_SAVE_DESELECT_SERIES = 'GRAPH_SAVE_DESELECT_SERIES';
export const GRAPH_SAVE_RESTORE_REDUCER = 'GRAPH_SAVE_RESTORE_REDUCER';
export const GRAPH_SAVE_CHART_REF = 'GRAPH_SAVE_CHART_REF';
export const GRAPH_SAVE_DELETE_OBJECT = 'GRAPH_SAVE_DELETE_OBJECT';

// Table
export const TABLE_UPDATE = 'TABLE_UPDATE';
export const TABLE_SAVE = 'TABLE_SAVE';
export const TABLE_DOWNLOAD = 'TABLE_DOWNLOAD';

// ERRORS
export const REPORT_ERROR = 'REPORT_ERROR';
export const REPORT_API_ERROR = 'REPORT_API_ERROR';
export const DISMISS_ERROR = 'DISMISS_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SHOW_ERRORS = 'SHOW_ERRORS';
export const HIDE_ERRORS = 'HIDE_ERRORS';

export const SHOW_LOGIN_ERROR = 'SHOW_LOGIN_ERROR';
export const CLOSE_LOGIN_ERROR = 'CLOSE_LOGIN_ERROR';

// ERROR STORE ACTIONS
export const ADD_ERROR = 'ADD_ERROR';

// SERIES

export const SERIES_EXPR_CREATE = 'SERIES_EXPR_CREATE';
export const SERIES_REF_CREATE = 'SERIES_REF_CREATE';
export const SERIES_DATA_CREATE = 'SERIES_DATA_CREATE';
export const SERIES_UPDATE = 'SERIES_UPDATE';
export const SERIES_RESOLVE = 'SERIES_RESOLVE';
export const SERIES_DELETE = 'SERIES_DELETE';

export const SERIES_SAVE_SERIES = 'SERIES_SAVE_SERIES';
export const SERIES_SAVE_RESOLVED_SERIES = 'SERIES_SAVE_RESOLVED_SERIES';
export const SERIES_SAVE_DELETE_SERIES = 'SERIES_SAVE_DELETE_SERIES';
export const SERIES_SAVE_UPDATE = 'SERIES_SAVE_UPDATE';
export const SERIES_SAVE_RESTORE_SERIES = 'SERIES_SAVE_RESTORE_SERIES';

export const SERIES_SIGNAL_UPDATED = 'SERIES_SIGNAL_UPDATED';
export const SERIES_SIGNAL_DELETED = 'SERIES_SIGNAL_DELETED';
export const SERIES_SIGNAL_RESOLVED = 'SERIES_SIGNAL_RESOLVED';
