export const VINTAGES_INITIATE = 'VINTAGES_INITIATE';
export const VINTAGES_FETCH_LIST = 'VINTAGES_FETCH_LIST';
export const VINTAGES_FETCH_OBJECT = 'VINTAGES_FETCH_OBJECT';
export const VINTAGES_LOAD_MORE = 'VINTAGES_LOAD_MORE';
export const VINTAGES_REFRESH_LIST = 'VINTAGES_REFRESH_LIST';

// store
export const VINTAGES_SAVE_LIST = 'VINTAGES_SAVE_LIST';
export const VINTAGES_SAVE_OBJECT = 'VINTAGES_SAVE_OBJECT';
export const VINTAGES_SAVE_HAS_PERMISSION = 'VINTAGES_SAVE_HAS_PERMISSION';
export const VINTAGES_SAVE_VINTAGE_SERIES = 'VINTAGES_SAVE_VINTAGE_SERIES';
export const VINTAGES_SAVE_VARIABLE = 'VINTAGES_SAVE_VARIABLE';
