export const API_SET_JWT = 'API_SET_JWT_TYPE';
export const API_SET_PARAMETERS = 'API_SET_PARAMETERS';

// Observations
export const FETCH_OBSERVATIONS = 'FETCH_OBSERVATIONS';
export const SAVE_OBSERVATIONS = 'FETCH_OBSERVATIONS';
