export const API_SET_JWT = 'API_SET_JWT_TYPE';
export const API_SET_PARAMETERS = 'API_SET_PARAMETERS';

// Observations
export const FETCH_OBSERVATIONS = 'FETCH_OBSERVATIONS';
export const SAVE_OBSERVATIONS = 'FETCH_OBSERVATIONS';

export const UPLOAD_INITIATE = 'UPLOAD_INITIATE';
export const UPLOAD_CREATE = 'UPLOAD_CREATE';
export const UPLOAD_FETCH_LIST = 'UPLOAD_FETCH_LIST';
export const UPLOAD_FETCH_OBJECT = 'UPLOAD_FETCH_OBJECT';
export const UPLOAD_FETCH_PENDING = 'UPLOAD_FETCH_PENDING';
export const UPLOAD_LOAD_MORE = 'UPLOAD_LOAD_MORE';
export const UPLOAD_REFRESH_LIST = 'UPLOAD_REFRESH_LIST';
export const UPLOAD_AUTO_REFRESH_OBJECT = 'UPLOAD_AUTO_REFRESH_OBJECT';
export const UPLOAD_AUTO_REFRESH_LIST = 'UPLOAD_AUTO_REFRESH_LIST';

// store
export const UPLOAD_SAVE_LIST = 'UPLOAD_SAVE_LIST';
export const UPLOAD_SAVE_OBJECT = 'UPLOAD_SAVE_OBJECT';
export const UPLOAD_SAVE_HAS_PERMISSION = 'UPLOAD_SAVE_HAS_PERMISSION';
