// when we update active layout
export const WORKBOOK_SAVE_MODEL = 'WORKBOOK_SAVE_MODEL';
export const WORKBOOK_SAVE_ANALYTICS_MODEL = 'WORKBOOK_SAVE_ANALYTICS_MODEL';
export const WORKBOOK_SAVE_TSB_MODEL = 'WORKBOOK_SAVE_TSB_MODEL';
export const WORKBOOK_SAVE_ACTIVE_LAYOUT = 'WORKBOOK_SAVE_ACTIVE_LAYOUT';
export const WORKBOOK_SAVE_ACTIVE_GRAPH_TABSET = 'WORKBOOK_SAVE_ACTIVE_GRAPH_TABSET';

export const WORKBOOK_CLOSE_GRAPH_TAB = 'WORKBOOK_CLOSE_GRAPH_TAB';
export const WORKBOOK_CLOSE_ANALYTICS_TAB = 'WORKBOOK_CLOSE_ANALYTICS_TAB';

export const WORKBOOK_ADD_ANALYTICS_TAB = 'WORKBOOK_ADD_ANALYTICS_TAB';
export const WORKBOOK_CREATE_ANALYTICS_TAB = 'WORKBOOK_CREATE_ANALYTICS_TAB';

export const WORKBOOK_ON_MODEL_CHANGE = 'WORKBOOK_ON_MODEL_CHANGE';
export const WORKBOOK_ON_ACTION = 'WORKBOOK_ON_ACTION';

// save active tabset
export const WORKBOOK_SWITCH_GRAPH_LAYOUTS = 'WORKBOOK_SWITCH_GRAPH_LAYOUTS';

// add tab in model
export const WORKBOOK_ADD_NEW_GRAPH_TAB = 'WORKBOOK_ADD_NEW_GRAPH_TAB';

export const WORKBOOK_CREATE_ANALYTICS_FROM_SERIES = 'WORKBOOK_CREATE_ANALYTICS_FROM_SERIES';
export const WORKBOOK_OPEN_ANALYTICS_BORDER_TAB = 'WORKBOOK_OPEN_ANALYTICS_BORDER_TAB';
export const UI_SAVE_TOUR_IS_TOUR_OPEN = 'UI_SAVE_TOUR_IS_TOUR_OPEN';

//
//  SERIES LIST
//
export const SERIESLIST_FUNC_EDITOR_SAVE_OPEN = 'SERIESLIST_FUNC_EDITOR_SAVE_OPEN';
export const SERIESLIST_FUNC_EDITOR_SAVE_CLOSE = 'SERIESLIST_FUNC_EDITOR_SAVE_CLOSE';
export const SERIESLIST_FUNC_EDITOR_SAVE_ERRORS = 'SERIESLIST_FUNC_EDITOR_SAVE_ERRORS';

export const SERIESLIST_FUNC_EDITOR_SAGE_CONFIRM_EXPR = 'SERIESLIST_FUNC_EDITOR_SAGE_CONFIRM_EXPR';
export const UI_SAVE_RESTORE_REDUCER = 'UI_SAVE_RESTORE_REDUCER';
//
// SERIES INFO
//
export const SERIESINFO_SAVE_ACTIVE_SERIES = 'SERIESINFO_SAVE_ACTIVE_SERIES';

//
//  WORKBOOK
//
export const WORKBOOK_UPDATE_METADATA = 'WORKBOOK_UPDATE_METADATA';
export const WORKBOOK_UPDATE_FAVORITE = 'WORKBOOK_UPDATE_FAVORITE';

// reducer
export const WORKBOOK_SAVE_METADATA = 'WORKBOOK_SAVE_METADATA';
export const WORKBOOK_SAVE_FAVORITE = 'WORKBOOK_SAVE_FAVORITE';
export const WORKBOOK_SAVE_WID = 'WORKBOOK_SAVE_WID';
export const WORKBOOK_GET_WORKBOOK = 'WORKBOOK_GET_WORKBOOK';
export const WORKBOOK_PUT_WORKBOOK = 'WORKBOOK_PUT_WORKBOOK';

// WORKBOOK UI
export const WORKBOOK_SAVE_WORKBOOK_UI_PROPS = 'WORKBOOK_SAVE_WORKBOOK_UI_PROPS';

export const WORKBOOK_OPEN_TIMESERIES_BROWSER = 'WORKBOOK_OPEN_TIMESERIES_BROWSER';
export const WORKBOOK_OPEN_UPLOAD = 'WORKBOOK_OPEN_UPLOAD';

// =======
// // // when we switch between layouts
// // export const WORKBOOK_SAVE_SWITCH_LAYOUT = 'WORKBOOK_SAVE_SWITCH_LAYOUT';

// // // when we update active layout
// // export const WORKBOOK_SAVE_UPDATE_LAYOUT = 'WORKBOOK_SAVE_UPDATE_LAYOUT';

// // // store tabset id
// // export const WORKBOOK_SAVE_SELECTED_TABSET = 'WORKBOOK_SAVE_SELECTED_TABSET';

// // // update analytics model
// // export const UPDATE_ANALYTICS_MODEL = 'UPDATE_ANALYTICS_MODEL';

// // // save active tabset
// // export const WORKBOOK_SAVE_ACTIVE_LAYOUT = 'WORKBOOK_SAVE_ACTIVE_LAYOUT';
// // //
// // //  STORAGE
// // //

// >>>>>>> dev/main
