/**
 * ChronosDB swagger
 * ChronosDB Analytics server
 *
 * The version of the OpenAPI document: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import WSeriesDownload from '../model/WSeriesDownload';

/**
* Series service.
* @module api/SeriesApi
* @version 0.1
*/
export default class SeriesApi {

    /**
    * Constructs a new SeriesApi. 
    * @alias module:api/SeriesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the analyticsApiDownloadDownload operation.
     * @callback module:api/SeriesApi~analyticsApiDownloadDownloadCallback
     * @param {String} error Error message, if any.
     * @param {File} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Download workbook series in a file
     * Download workbook series in a file
     * @param {module:model/WSeriesDownload} wSeriesDownload 
     * @param {module:api/SeriesApi~analyticsApiDownloadDownloadCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link File}
     */
    analyticsApiDownloadDownload(wSeriesDownload, callback) {
      let postBody = wSeriesDownload;
      // verify the required parameter 'wSeriesDownload' is set
      if (wSeriesDownload === undefined || wSeriesDownload === null) {
        throw new Error("Missing the required parameter 'wSeriesDownload' when calling analyticsApiDownloadDownload");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['api_key', 'jwt'];
      let contentTypes = ['application/json'];
      let accepts = ['application/octet-stream'];
      let returnType = File;
      return this.apiClient.callApi(
        '/download', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
