/**
 * ChronosDB swagger
 * ChronosDB Analytics server
 *
 * The version of the OpenAPI document: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ADFullerResult model module.
 * @module model/ADFullerResult
 * @version 0.1
 */
class ADFullerResult {
    /**
     * Constructs a new <code>ADFullerResult</code>.
     * @alias module:model/ADFullerResult
     */
    constructor() { 
        
        ADFullerResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ADFullerResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ADFullerResult} obj Optional instance to populate.
     * @return {module:model/ADFullerResult} The populated <code>ADFullerResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ADFullerResult();

            if (data.hasOwnProperty('stat')) {
                obj['stat'] = ApiClient.convertToType(data['stat'], 'Number');
            }
            if (data.hasOwnProperty('pvalue')) {
                obj['pvalue'] = ApiClient.convertToType(data['pvalue'], Object);
            }
            if (data.hasOwnProperty('usedlag')) {
                obj['usedlag'] = ApiClient.convertToType(data['usedlag'], 'Number');
            }
            if (data.hasOwnProperty('nobs')) {
                obj['nobs'] = ApiClient.convertToType(data['nobs'], 'Number');
            }
            if (data.hasOwnProperty('icbest')) {
                obj['icbest'] = ApiClient.convertToType(data['icbest'], 'Number');
            }
            if (data.hasOwnProperty('critical')) {
                obj['critical'] = ApiClient.convertToType(data['critical'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * test statistics
 * @member {Number} stat
 */
ADFullerResult.prototype['stat'] = undefined;

/**
 * MacKinnon’s approximate p-value based on MacKinnon (1994, 2010)
 * @member {Object} pvalue
 */
ADFullerResult.prototype['pvalue'] = undefined;

/**
 * number of lags used
 * @member {Number} usedlag
 */
ADFullerResult.prototype['usedlag'] = undefined;

/**
 * number of observations
 * @member {Number} nobs
 */
ADFullerResult.prototype['nobs'] = undefined;

/**
 * the value of the best information criterio if used
 * @member {Number} icbest
 */
ADFullerResult.prototype['icbest'] = undefined;

/**
 * Critical values for the test statistic at the 1 %, 5 %, and 10 % levels. Based on MacKinnon (2010).
 * @member {Array.<Number>} critical
 */
ADFullerResult.prototype['critical'] = undefined;






export default ADFullerResult;

