/**
 * ChronosDB swagger
 * ChronosDB Analytics server
 *
 * The version of the OpenAPI document: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ARResultHet model module.
 * @module model/ARResultHet
 * @version 0.1
 */
class ARResultHet {
    /**
     * Constructs a new <code>ARResultHet</code>.
     * @alias module:model/ARResultHet
     */
    constructor() { 
        
        ARResultHet.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ARResultHet</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ARResultHet} obj Optional instance to populate.
     * @return {module:model/ARResultHet} The populated <code>ARResultHet</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ARResultHet();

            if (data.hasOwnProperty('archlm')) {
                obj['archlm'] = ApiClient.convertToType(data['archlm'], 'Number');
            }
            if (data.hasOwnProperty('pv')) {
                obj['pv'] = ApiClient.convertToType(data['pv'], 'Number');
            }
            if (data.hasOwnProperty('df')) {
                obj['df'] = ApiClient.convertToType(data['df'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} archlm
 */
ARResultHet.prototype['archlm'] = undefined;

/**
 * @member {Number} pv
 */
ARResultHet.prototype['pv'] = undefined;

/**
 * @member {Number} df
 */
ARResultHet.prototype['df'] = undefined;






export default ARResultHet;

