/**
 * ChronosDB swagger
 * ChronosDB Analytics server
 *
 * The version of the OpenAPI document: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ARResponseAllOf from './ARResponseAllOf';
import ARResult from './ARResult';
import AnalyticsResponse from './AnalyticsResponse';

/**
 * The ARResponse model module.
 * @module model/ARResponse
 * @version 0.1
 */
class ARResponse {
    /**
     * Constructs a new <code>ARResponse</code>.
     * @alias module:model/ARResponse
     * @implements module:model/AnalyticsResponse
     * @implements module:model/ARResponseAllOf
     */
    constructor() { 
        AnalyticsResponse.initialize(this);ARResponseAllOf.initialize(this);
        ARResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ARResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ARResponse} obj Optional instance to populate.
     * @return {module:model/ARResponse} The populated <code>ARResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ARResponse();
            AnalyticsResponse.constructFromObject(data, obj);
            ARResponseAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Date');
            }
            if (data.hasOwnProperty('result')) {
                obj['result'] = ARResult.constructFromObject(data['result']);
            }
            if (data.hasOwnProperty('warnings')) {
                obj['warnings'] = ApiClient.convertToType(data['warnings'], ['String']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], [Object]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
ARResponse.prototype['id'] = undefined;

/**
 * @member {Date} timestamp
 */
ARResponse.prototype['timestamp'] = undefined;

/**
 * @member {module:model/ARResult} result
 */
ARResponse.prototype['result'] = undefined;

/**
 * @member {Array.<String>} warnings
 */
ARResponse.prototype['warnings'] = undefined;

/**
 * @member {module:model/ARResponse.StatusEnum} status
 */
ARResponse.prototype['status'] = undefined;

/**
 * @member {Array.<Object>} errors
 */
ARResponse.prototype['errors'] = undefined;


// Implement AnalyticsResponse interface:
/**
 * @member {String} id
 */
AnalyticsResponse.prototype['id'] = undefined;
/**
 * @member {Date} timestamp
 */
AnalyticsResponse.prototype['timestamp'] = undefined;
/**
 * @member {Object} result
 */
AnalyticsResponse.prototype['result'] = undefined;
/**
 * @member {Array.<String>} warnings
 */
AnalyticsResponse.prototype['warnings'] = undefined;
/**
 * @member {module:model/AnalyticsResponse.StatusEnum} status
 */
AnalyticsResponse.prototype['status'] = undefined;
/**
 * @member {Array.<Object>} errors
 */
AnalyticsResponse.prototype['errors'] = undefined;
// Implement ARResponseAllOf interface:
/**
 * @member {module:model/ARResult} result
 */
ARResponseAllOf.prototype['result'] = undefined;



/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
ARResponse['StatusEnum'] = {

    /**
     * value: "success"
     * @const
     */
    "success": "success",

    /**
     * value: "failed"
     * @const
     */
    "failed": "failed"
};



export default ARResponse;

