/**
 * ChronosDB swagger
 * ChronosDB Analytics server
 *
 * The version of the OpenAPI document: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AnalyticsResponse from './AnalyticsResponse';
import BKFilterResponseAllOf from './BKFilterResponseAllOf';
import BKFilterResult from './BKFilterResult';

/**
 * The BKFilterResponse model module.
 * @module model/BKFilterResponse
 * @version 0.1
 */
class BKFilterResponse {
    /**
     * Constructs a new <code>BKFilterResponse</code>.
     * BKFilter response
     * @alias module:model/BKFilterResponse
     * @implements module:model/AnalyticsResponse
     * @implements module:model/BKFilterResponseAllOf
     */
    constructor() { 
        AnalyticsResponse.initialize(this);BKFilterResponseAllOf.initialize(this);
        BKFilterResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BKFilterResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BKFilterResponse} obj Optional instance to populate.
     * @return {module:model/BKFilterResponse} The populated <code>BKFilterResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BKFilterResponse();
            AnalyticsResponse.constructFromObject(data, obj);
            BKFilterResponseAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Date');
            }
            if (data.hasOwnProperty('result')) {
                obj['result'] = BKFilterResult.constructFromObject(data['result']);
            }
            if (data.hasOwnProperty('warnings')) {
                obj['warnings'] = ApiClient.convertToType(data['warnings'], ['String']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], [Object]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
BKFilterResponse.prototype['id'] = undefined;

/**
 * @member {Date} timestamp
 */
BKFilterResponse.prototype['timestamp'] = undefined;

/**
 * @member {module:model/BKFilterResult} result
 */
BKFilterResponse.prototype['result'] = undefined;

/**
 * @member {Array.<String>} warnings
 */
BKFilterResponse.prototype['warnings'] = undefined;

/**
 * @member {module:model/BKFilterResponse.StatusEnum} status
 */
BKFilterResponse.prototype['status'] = undefined;

/**
 * @member {Array.<Object>} errors
 */
BKFilterResponse.prototype['errors'] = undefined;


// Implement AnalyticsResponse interface:
/**
 * @member {String} id
 */
AnalyticsResponse.prototype['id'] = undefined;
/**
 * @member {Date} timestamp
 */
AnalyticsResponse.prototype['timestamp'] = undefined;
/**
 * @member {Object} result
 */
AnalyticsResponse.prototype['result'] = undefined;
/**
 * @member {Array.<String>} warnings
 */
AnalyticsResponse.prototype['warnings'] = undefined;
/**
 * @member {module:model/AnalyticsResponse.StatusEnum} status
 */
AnalyticsResponse.prototype['status'] = undefined;
/**
 * @member {Array.<Object>} errors
 */
AnalyticsResponse.prototype['errors'] = undefined;
// Implement BKFilterResponseAllOf interface:
/**
 * @member {module:model/BKFilterResult} result
 */
BKFilterResponseAllOf.prototype['result'] = undefined;



/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
BKFilterResponse['StatusEnum'] = {

    /**
     * value: "success"
     * @const
     */
    "success": "success",

    /**
     * value: "failed"
     * @const
     */
    "failed": "failed"
};



export default BKFilterResponse;

