/**
 * ChronosDB swagger
 * ChronosDB Analytics server
 *
 * The version of the OpenAPI document: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WSeries from './WSeries';

/**
 * The BKFilterResult model module.
 * @module model/BKFilterResult
 * @version 0.1
 */
class BKFilterResult {
    /**
     * Constructs a new <code>BKFilterResult</code>.
     * @alias module:model/BKFilterResult
     */
    constructor() { 
        
        BKFilterResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BKFilterResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BKFilterResult} obj Optional instance to populate.
     * @return {module:model/BKFilterResult} The populated <code>BKFilterResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BKFilterResult();

            if (data.hasOwnProperty('cycle')) {
                obj['cycle'] = WSeries.constructFromObject(data['cycle']);
            }
            if (data.hasOwnProperty('low')) {
                obj['low'] = ApiClient.convertToType(data['low'], 'Number');
            }
            if (data.hasOwnProperty('high')) {
                obj['high'] = ApiClient.convertToType(data['high'], 'Number');
            }
            if (data.hasOwnProperty('k')) {
                obj['k'] = ApiClient.convertToType(data['k'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/WSeries} cycle
 */
BKFilterResult.prototype['cycle'] = undefined;

/**
 * @member {Number} low
 */
BKFilterResult.prototype['low'] = undefined;

/**
 * @member {Number} high
 */
BKFilterResult.prototype['high'] = undefined;

/**
 * @member {Number} k
 */
BKFilterResult.prototype['k'] = undefined;






export default BKFilterResult;

