/**
 * ChronosDB swagger
 * ChronosDB Analytics server
 *
 * The version of the OpenAPI document: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WSeries from './WSeries';

/**
 * The CFFilterResult model module.
 * @module model/CFFilterResult
 * @version 0.1
 */
class CFFilterResult {
    /**
     * Constructs a new <code>CFFilterResult</code>.
     * @alias module:model/CFFilterResult
     */
    constructor() { 
        
        CFFilterResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CFFilterResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CFFilterResult} obj Optional instance to populate.
     * @return {module:model/CFFilterResult} The populated <code>CFFilterResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CFFilterResult();

            if (data.hasOwnProperty('cycle')) {
                obj['cycle'] = WSeries.constructFromObject(data['cycle']);
            }
            if (data.hasOwnProperty('trend')) {
                obj['trend'] = WSeries.constructFromObject(data['trend']);
            }
            if (data.hasOwnProperty('low')) {
                obj['low'] = ApiClient.convertToType(data['low'], 'Number');
            }
            if (data.hasOwnProperty('high')) {
                obj['high'] = ApiClient.convertToType(data['high'], 'Number');
            }
            if (data.hasOwnProperty('drift')) {
                obj['drift'] = ApiClient.convertToType(data['drift'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/WSeries} cycle
 */
CFFilterResult.prototype['cycle'] = undefined;

/**
 * @member {module:model/WSeries} trend
 */
CFFilterResult.prototype['trend'] = undefined;

/**
 * @member {Number} low
 */
CFFilterResult.prototype['low'] = undefined;

/**
 * @member {Number} high
 */
CFFilterResult.prototype['high'] = undefined;

/**
 * @member {Boolean} drift
 */
CFFilterResult.prototype['drift'] = undefined;






export default CFFilterResult;

