/**
 * ChronosDB swagger
 * ChronosDB Analytics server
 *
 * The version of the OpenAPI document: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CFFilterResult from './CFFilterResult';

/**
 * The CFFilterResponseAllOf model module.
 * @module model/CFFilterResponseAllOf
 * @version 0.1
 */
class CFFilterResponseAllOf {
    /**
     * Constructs a new <code>CFFilterResponseAllOf</code>.
     * @alias module:model/CFFilterResponseAllOf
     */
    constructor() { 
        
        CFFilterResponseAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CFFilterResponseAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CFFilterResponseAllOf} obj Optional instance to populate.
     * @return {module:model/CFFilterResponseAllOf} The populated <code>CFFilterResponseAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CFFilterResponseAllOf();

            if (data.hasOwnProperty('result')) {
                obj['result'] = CFFilterResult.constructFromObject(data['result']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/CFFilterResult} result
 */
CFFilterResponseAllOf.prototype['result'] = undefined;






export default CFFilterResponseAllOf;

