/**
 * ChronosDB swagger
 * ChronosDB Analytics server
 *
 * The version of the OpenAPI document: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DescriptiveResult from './DescriptiveResult';

/**
 * The DescriptiveResponseAllOf model module.
 * @module model/DescriptiveResponseAllOf
 * @version 0.1
 */
class DescriptiveResponseAllOf {
    /**
     * Constructs a new <code>DescriptiveResponseAllOf</code>.
     * @alias module:model/DescriptiveResponseAllOf
     */
    constructor() { 
        
        DescriptiveResponseAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DescriptiveResponseAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DescriptiveResponseAllOf} obj Optional instance to populate.
     * @return {module:model/DescriptiveResponseAllOf} The populated <code>DescriptiveResponseAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DescriptiveResponseAllOf();

            if (data.hasOwnProperty('result')) {
                obj['result'] = DescriptiveResult.constructFromObject(data['result']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/DescriptiveResult} result
 */
DescriptiveResponseAllOf.prototype['result'] = undefined;






export default DescriptiveResponseAllOf;

