/**
 * ChronosDB swagger
 * ChronosDB Analytics server
 *
 * The version of the OpenAPI document: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GrangerResultsStats from './GrangerResultsStats';

/**
 * The GrangerResults model module.
 * @module model/GrangerResults
 * @version 0.1
 */
class GrangerResults {
    /**
     * Constructs a new <code>GrangerResults</code>.
     * @alias module:model/GrangerResults
     */
    constructor() { 
        
        GrangerResults.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GrangerResults</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GrangerResults} obj Optional instance to populate.
     * @return {module:model/GrangerResults} The populated <code>GrangerResults</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GrangerResults();

            if (data.hasOwnProperty('stats')) {
                obj['stats'] = ApiClient.convertToType(data['stats'], {'String': GrangerResultsStats});
            }
        }
        return obj;
    }


}

/**
 * t-statistics of unit-root test
 * @member {Object.<String, module:model/GrangerResultsStats>} stats
 */
GrangerResults.prototype['stats'] = undefined;






export default GrangerResults;

