/**
 * ChronosDB swagger
 * ChronosDB Analytics server
 *
 * The version of the OpenAPI document: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WSeries from './WSeries';

/**
 * The GrangerParameters model module.
 * @module model/GrangerParameters
 * @version 0.1
 */
class GrangerParameters {
    /**
     * Constructs a new <code>GrangerParameters</code>.
     * @alias module:model/GrangerParameters
     */
    constructor() { 
        
        GrangerParameters.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GrangerParameters</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GrangerParameters} obj Optional instance to populate.
     * @return {module:model/GrangerParameters} The populated <code>GrangerParameters</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GrangerParameters();

            if (data.hasOwnProperty('x')) {
                obj['x'] = WSeries.constructFromObject(data['x']);
            }
            if (data.hasOwnProperty('y')) {
                obj['y'] = WSeries.constructFromObject(data['y']);
            }
            if (data.hasOwnProperty('maxlag')) {
                obj['maxlag'] = ApiClient.convertToType(data['maxlag'], 'Number');
            }
            if (data.hasOwnProperty('dropna')) {
                obj['dropna'] = ApiClient.convertToType(data['dropna'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/WSeries} x
 */
GrangerParameters.prototype['x'] = undefined;

/**
 * @member {module:model/WSeries} y
 */
GrangerParameters.prototype['y'] = undefined;

/**
 * Maximum lag which is included in test, default 12*(nobs/100)^{1/4}.
 * @member {Number} maxlag
 */
GrangerParameters.prototype['maxlag'] = undefined;

/**
 * Drop missing values; any observations with NaNs are dropped.
 * @member {Boolean} dropna
 */
GrangerParameters.prototype['dropna'] = undefined;






export default GrangerParameters;

