/**
 * ChronosDB swagger
 * ChronosDB Analytics server
 *
 * The version of the OpenAPI document: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WSeries from './WSeries';

/**
 * The HPFilterParameters model module.
 * @module model/HPFilterParameters
 * @version 0.1
 */
class HPFilterParameters {
    /**
     * Constructs a new <code>HPFilterParameters</code>.
     * @alias module:model/HPFilterParameters
     */
    constructor() { 
        
        HPFilterParameters.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HPFilterParameters</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HPFilterParameters} obj Optional instance to populate.
     * @return {module:model/HPFilterParameters} The populated <code>HPFilterParameters</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HPFilterParameters();

            if (data.hasOwnProperty('x')) {
                obj['x'] = WSeries.constructFromObject(data['x']);
            }
            if (data.hasOwnProperty('lambda')) {
                obj['lambda'] = ApiClient.convertToType(data['lambda'], 'Number');
            }
            if (data.hasOwnProperty('dropna')) {
                obj['dropna'] = ApiClient.convertToType(data['dropna'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/WSeries} x
 */
HPFilterParameters.prototype['x'] = undefined;

/**
 * The Hodrick-Prescott smoothing parameter. A value of 1600 is suggested for quarterly data. Ravn and Uhlig suggest using a value of 6.25 (1600/4**4) for annual data and 129600 (1600*3**4) for monthly data.
 * @member {Number} lambda
 */
HPFilterParameters.prototype['lambda'] = undefined;

/**
 * Drop missing values; any observations with NaNs are dropped.
 * @member {Boolean} dropna
 */
HPFilterParameters.prototype['dropna'] = undefined;






export default HPFilterParameters;

