/**
 * ChronosDB swagger
 * ChronosDB Analytics server
 *
 * The version of the OpenAPI document: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LMUnitrootResponseAllOf model module.
 * @module model/LMUnitrootResponseAllOf
 * @version 0.1
 */
class LMUnitrootResponseAllOf {
    /**
     * Constructs a new <code>LMUnitrootResponseAllOf</code>.
     * @alias module:model/LMUnitrootResponseAllOf
     */
    constructor() { 
        
        LMUnitrootResponseAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LMUnitrootResponseAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LMUnitrootResponseAllOf} obj Optional instance to populate.
     * @return {module:model/LMUnitrootResponseAllOf} The populated <code>LMUnitrootResponseAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LMUnitrootResponseAllOf();

            if (data.hasOwnProperty('result')) {
                obj['result'] = ApiClient.convertToType(data['result'], {'String': Object});
            }
        }
        return obj;
    }


}

/**
 * @member {Object.<String, Object>} result
 */
LMUnitrootResponseAllOf.prototype['result'] = undefined;






export default LMUnitrootResponseAllOf;

