/**
 * ChronosDB swagger
 * ChronosDB Analytics server
 *
 * The version of the OpenAPI document: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WSeries from './WSeries';

/**
 * The PPParameters model module.
 * @module model/PPParameters
 * @version 0.1
 */
class PPParameters {
    /**
     * Constructs a new <code>PPParameters</code>.
     * @alias module:model/PPParameters
     */
    constructor() { 
        
        PPParameters.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PPParameters</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PPParameters} obj Optional instance to populate.
     * @return {module:model/PPParameters} The populated <code>PPParameters</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PPParameters();

            if (data.hasOwnProperty('x')) {
                obj['x'] = WSeries.constructFromObject(data['x']);
            }
            if (data.hasOwnProperty('autolag')) {
                obj['autolag'] = ApiClient.convertToType(data['autolag'], 'String');
            }
            if (data.hasOwnProperty('nlags')) {
                obj['nlags'] = ApiClient.convertToType(data['nlags'], 'Number');
            }
            if (data.hasOwnProperty('regression')) {
                obj['regression'] = ApiClient.convertToType(data['regression'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('dropna')) {
                obj['dropna'] = ApiClient.convertToType(data['dropna'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/WSeries} x
 */
PPParameters.prototype['x'] = undefined;

/**
 * Method to determine the number of lags: `auto`: lags is calculated using int(12 * (n / 100)**(1 / 4)). `nlags`: nlags is used for the number of lags 
 * @member {module:model/PPParameters.AutolagEnum} autolag
 * @default 'auto'
 */
PPParameters.prototype['autolag'] = 'auto';

/**
 * Maximum lag which is included in test.
 * @member {Number} nlags
 */
PPParameters.prototype['nlags'] = undefined;

/**
 * Constant and trend order to include in regression. ‘nc’ : no constant, no trend. ‘c’ : constant only (default). ‘ct’ : constant and trend.
 * @member {module:model/PPParameters.RegressionEnum} regression
 * @default 'c'
 */
PPParameters.prototype['regression'] = 'c';

/**
 * Test statistics: ‘tau’ : t-stat. ‘rho’ : a test based on nobs times the re-centered regression coefficient.
 * @member {module:model/PPParameters.TypeEnum} type
 * @default 'tau'
 */
PPParameters.prototype['type'] = 'tau';

/**
 * Drop missing values; any observations with NaNs are dropped.
 * @member {Boolean} dropna
 */
PPParameters.prototype['dropna'] = undefined;





/**
 * Allowed values for the <code>autolag</code> property.
 * @enum {String}
 * @readonly
 */
PPParameters['AutolagEnum'] = {

    /**
     * value: "auto"
     * @const
     */
    "auto": "auto",

    /**
     * value: "nlags"
     * @const
     */
    "nlags": "nlags"
};


/**
 * Allowed values for the <code>regression</code> property.
 * @enum {String}
 * @readonly
 */
PPParameters['RegressionEnum'] = {

    /**
     * value: "nc"
     * @const
     */
    "nc": "nc",

    /**
     * value: "c"
     * @const
     */
    "c": "c",

    /**
     * value: "ct"
     * @const
     */
    "ct": "ct"
};


/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
PPParameters['TypeEnum'] = {

    /**
     * value: "tau"
     * @const
     */
    "tau": "tau",

    /**
     * value: "rho"
     * @const
     */
    "rho": "rho"
};



export default PPParameters;

