/**
 * ChronosDB swagger
 * ChronosDB Analytics server
 *
 * The version of the OpenAPI document: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Sample model module.
 * @module model/Sample
 * @version 0.1
 */
class Sample {
    /**
     * Constructs a new <code>Sample</code>.
     * @alias module:model/Sample
     */
    constructor() { 
        
        Sample.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Sample</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Sample} obj Optional instance to populate.
     * @return {module:model/Sample} The populated <code>Sample</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Sample();

            if (data.hasOwnProperty('start')) {
                obj['start'] = ApiClient.convertToType(data['start'], 'Date');
            }
            if (data.hasOwnProperty('end')) {
                obj['end'] = ApiClient.convertToType(data['end'], 'Date');
            }
            if (data.hasOwnProperty('nobs')) {
                obj['nobs'] = ApiClient.convertToType(data['nobs'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * sample start date
 * @member {Date} start
 */
Sample.prototype['start'] = undefined;

/**
 * sample end date
 * @member {Date} end
 */
Sample.prototype['end'] = undefined;

/**
 * number of observations
 * @member {Number} nobs
 */
Sample.prototype['nobs'] = undefined;






export default Sample;

