/**
 * ChronosDB swagger
 * ChronosDB Analytics server
 *
 * The version of the OpenAPI document: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DType from './DType';
import Frequency from './Frequency';
import IType from './IType';

/**
 * The Timeseries model module.
 * @module model/Timeseries
 * @version 0.1
 */
class Timeseries {
    /**
     * Constructs a new <code>Timeseries</code>.
     * @alias module:model/Timeseries
     */
    constructor() { 
        
        Timeseries.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Timeseries</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Timeseries} obj Optional instance to populate.
     * @return {module:model/Timeseries} The populated <code>Timeseries</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Timeseries();

            if (data.hasOwnProperty('tsid')) {
                obj['tsid'] = ApiClient.convertToType(data['tsid'], 'String');
            }
            if (data.hasOwnProperty('collId')) {
                obj['collId'] = ApiClient.convertToType(data['collId'], 'String');
            }
            if (data.hasOwnProperty('dtype')) {
                obj['dtype'] = DType.constructFromObject(data['dtype']);
            }
            if (data.hasOwnProperty('dparams')) {
                obj['dparams'] = ApiClient.convertToType(data['dparams'], Object);
            }
            if (data.hasOwnProperty('itype')) {
                obj['itype'] = IType.constructFromObject(data['itype']);
            }
            if (data.hasOwnProperty('freq')) {
                obj['freq'] = Frequency.constructFromObject(data['freq']);
            }
            if (data.hasOwnProperty('fparams')) {
                obj['fparams'] = ApiClient.convertToType(data['fparams'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {String} tsid
 */
Timeseries.prototype['tsid'] = undefined;

/**
 * @member {String} collId
 */
Timeseries.prototype['collId'] = undefined;

/**
 * @member {module:model/DType} dtype
 */
Timeseries.prototype['dtype'] = undefined;

/**
 * parameters of data type, e.g. enum
 * @member {Object} dparams
 */
Timeseries.prototype['dparams'] = undefined;

/**
 * @member {module:model/IType} itype
 */
Timeseries.prototype['itype'] = undefined;

/**
 * @member {module:model/Frequency} freq
 */
Timeseries.prototype['freq'] = undefined;

/**
 * parameters of time index type, e.g. time zone if applicable, pivot date, etc
 * @member {Object} fparams
 */
Timeseries.prototype['fparams'] = undefined;






export default Timeseries;

