/**
 * ChronosDB swagger
 * ChronosDB Analytics server
 *
 * The version of the OpenAPI document: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TSAResult model module.
 * @module model/TSAResult
 * @version 0.1
 */
class TSAResult {
    /**
     * Constructs a new <code>TSAResult</code>.
     * @alias module:model/TSAResult
     */
    constructor() { 
        
        TSAResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TSAResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TSAResult} obj Optional instance to populate.
     * @return {module:model/TSAResult} The populated <code>TSAResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TSAResult();

            if (data.hasOwnProperty('coeff')) {
                obj['coeff'] = ApiClient.convertToType(data['coeff'], [Object]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<Object>} coeff
 */
TSAResult.prototype['coeff'] = undefined;






export default TSAResult;

