/**
 * ChronosDB swagger
 * ChronosDB Analytics server
 *
 * The version of the OpenAPI document: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Frequency from './Frequency';
import WSeries from './WSeries';

/**
 * The WSeriesDownload model module.
 * @module model/WSeriesDownload
 * @version 0.1
 */
class WSeriesDownload {
    /**
     * Constructs a new <code>WSeriesDownload</code>.
     * @alias module:model/WSeriesDownload
     * @param freq {module:model/Frequency} 
     * @param fileFormat {module:model/WSeriesDownload.FileFormatEnum} 
     * @param series {Array.<module:model/WSeries>} List of WSeries
     */
    constructor(freq, fileFormat, series) { 
        
        WSeriesDownload.initialize(this, freq, fileFormat, series);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, freq, fileFormat, series) { 
        obj['freq'] = freq;
        obj['file_format'] = fileFormat;
        obj['series'] = series;
    }

    /**
     * Constructs a <code>WSeriesDownload</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WSeriesDownload} obj Optional instance to populate.
     * @return {module:model/WSeriesDownload} The populated <code>WSeriesDownload</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WSeriesDownload();

            if (data.hasOwnProperty('freq')) {
                obj['freq'] = Frequency.constructFromObject(data['freq']);
            }
            if (data.hasOwnProperty('file_name')) {
                obj['file_name'] = ApiClient.convertToType(data['file_name'], 'String');
            }
            if (data.hasOwnProperty('file_format')) {
                obj['file_format'] = ApiClient.convertToType(data['file_format'], 'String');
            }
            if (data.hasOwnProperty('series')) {
                obj['series'] = ApiClient.convertToType(data['series'], [WSeries]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Frequency} freq
 */
WSeriesDownload.prototype['freq'] = undefined;

/**
 * @member {String} file_name
 */
WSeriesDownload.prototype['file_name'] = undefined;

/**
 * @member {module:model/WSeriesDownload.FileFormatEnum} file_format
 */
WSeriesDownload.prototype['file_format'] = undefined;

/**
 * List of WSeries
 * @member {Array.<module:model/WSeries>} series
 */
WSeriesDownload.prototype['series'] = undefined;





/**
 * Allowed values for the <code>file_format</code> property.
 * @enum {String}
 * @readonly
 */
WSeriesDownload['FileFormatEnum'] = {

    /**
     * value: "csv"
     * @const
     */
    "csv": "csv",

    /**
     * value: "xlsx"
     * @const
     */
    "xlsx": "xlsx"
};



export default WSeriesDownload;

