/**
 * ChronosDB swagger
 * ChronosDB time series database API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The APIKey model module.
 * @module model/APIKey
 * @version 0.1
 */
class APIKey {
    /**
     * Constructs a new <code>APIKey</code>.
     * @alias module:model/APIKey
     */
    constructor() { 
        
        APIKey.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>APIKey</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/APIKey} obj Optional instance to populate.
     * @return {module:model/APIKey} The populated <code>APIKey</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new APIKey();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('prefix')) {
                obj['prefix'] = ApiClient.convertToType(data['prefix'], 'String');
            }
            if (data.hasOwnProperty('scopes')) {
                obj['scopes'] = ApiClient.convertToType(data['scopes'], ['String']);
            }
            if (data.hasOwnProperty('createdOn')) {
                obj['createdOn'] = ApiClient.convertToType(data['createdOn'], 'Date');
            }
            if (data.hasOwnProperty('expiriesOn')) {
                obj['expiriesOn'] = ApiClient.convertToType(data['expiriesOn'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
APIKey.prototype['name'] = undefined;

/**
 * @member {String} key
 */
APIKey.prototype['key'] = undefined;

/**
 * @member {String} prefix
 */
APIKey.prototype['prefix'] = undefined;

/**
 * @member {Array.<String>} scopes
 */
APIKey.prototype['scopes'] = undefined;

/**
 * @member {Date} createdOn
 */
APIKey.prototype['createdOn'] = undefined;

/**
 * @member {Date} expiriesOn
 */
APIKey.prototype['expiriesOn'] = undefined;






export default APIKey;

