/**
 * ChronosDB swagger
 * ChronosDB time series database API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CollectionObj model module.
 * @module model/CollectionObj
 * @version 0.1
 */
class CollectionObj {
    /**
     * Constructs a new <code>CollectionObj</code>.
     * @alias module:model/CollectionObj
     * @param collId {String} 
     * @param name {String} 
     */
    constructor(collId, name) { 
        
        CollectionObj.initialize(this, collId, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, collId, name) { 
        obj['coll_id'] = collId;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>CollectionObj</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CollectionObj} obj Optional instance to populate.
     * @return {module:model/CollectionObj} The populated <code>CollectionObj</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CollectionObj();

            if (data.hasOwnProperty('coll_id')) {
                obj['coll_id'] = ApiClient.convertToType(data['coll_id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} coll_id
 */
CollectionObj.prototype['coll_id'] = undefined;

/**
 * @member {String} name
 */
CollectionObj.prototype['name'] = undefined;






export default CollectionObj;

