/**
 * ChronosDB swagger
 * ChronosDB time series database API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Member from './Member';
import Visibility from './Visibility';

/**
 * The GroupHistorical model module.
 * @module model/GroupHistorical
 * @version 0.1
 */
class GroupHistorical {
    /**
     * Constructs a new <code>GroupHistorical</code>.
     * @alias module:model/GroupHistorical
     */
    constructor() { 
        
        GroupHistorical.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GroupHistorical</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GroupHistorical} obj Optional instance to populate.
     * @return {module:model/GroupHistorical} The populated <code>GroupHistorical</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GroupHistorical();

            if (data.hasOwnProperty('gid')) {
                obj['gid'] = ApiClient.convertToType(data['gid'], 'String');
            }
            if (data.hasOwnProperty('groupname')) {
                obj['groupname'] = ApiClient.convertToType(data['groupname'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('organization')) {
                obj['organization'] = ApiClient.convertToType(data['organization'], 'String');
            }
            if (data.hasOwnProperty('location')) {
                obj['location'] = ApiClient.convertToType(data['location'], 'String');
            }
            if (data.hasOwnProperty('website')) {
                obj['website'] = ApiClient.convertToType(data['website'], 'String');
            }
            if (data.hasOwnProperty('visibility')) {
                obj['visibility'] = Visibility.constructFromObject(data['visibility']);
            }
            if (data.hasOwnProperty('members')) {
                obj['members'] = ApiClient.convertToType(data['members'], [Member]);
            }
            if (data.hasOwnProperty('deleted')) {
                obj['deleted'] = ApiClient.convertToType(data['deleted'], 'Boolean');
            }
            if (data.hasOwnProperty('realStart')) {
                obj['realStart'] = ApiClient.convertToType(data['realStart'], 'Date');
            }
            if (data.hasOwnProperty('realEnd')) {
                obj['realEnd'] = ApiClient.convertToType(data['realEnd'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} gid
 */
GroupHistorical.prototype['gid'] = undefined;

/**
 * @member {String} groupname
 */
GroupHistorical.prototype['groupname'] = undefined;

/**
 * @member {String} email
 */
GroupHistorical.prototype['email'] = undefined;

/**
 * @member {String} description
 */
GroupHistorical.prototype['description'] = undefined;

/**
 * @member {String} organization
 */
GroupHistorical.prototype['organization'] = undefined;

/**
 * @member {String} location
 */
GroupHistorical.prototype['location'] = undefined;

/**
 * @member {String} website
 */
GroupHistorical.prototype['website'] = undefined;

/**
 * @member {module:model/Visibility} visibility
 */
GroupHistorical.prototype['visibility'] = undefined;

/**
 * @member {Array.<module:model/Member>} members
 */
GroupHistorical.prototype['members'] = undefined;

/**
 * time when the time series definition is valid from
 * @member {Boolean} deleted
 */
GroupHistorical.prototype['deleted'] = undefined;

/**
 * time when the time series definition is valid from
 * @member {Date} realStart
 */
GroupHistorical.prototype['realStart'] = undefined;

/**
 * time when the time series definition is valid until
 * @member {Date} realEnd
 */
GroupHistorical.prototype['realEnd'] = undefined;






export default GroupHistorical;

