/**
 * ChronosDB swagger
 * ChronosDB time series database API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Visibility from './Visibility';

/**
 * The GroupUpdate model module.
 * @module model/GroupUpdate
 * @version 0.1
 */
class GroupUpdate {
    /**
     * Constructs a new <code>GroupUpdate</code>.
     * @alias module:model/GroupUpdate
     */
    constructor() { 
        
        GroupUpdate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GroupUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GroupUpdate} obj Optional instance to populate.
     * @return {module:model/GroupUpdate} The populated <code>GroupUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GroupUpdate();

            if (data.hasOwnProperty('groupname')) {
                obj['groupname'] = ApiClient.convertToType(data['groupname'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('organization')) {
                obj['organization'] = ApiClient.convertToType(data['organization'], 'String');
            }
            if (data.hasOwnProperty('location')) {
                obj['location'] = ApiClient.convertToType(data['location'], 'String');
            }
            if (data.hasOwnProperty('website')) {
                obj['website'] = ApiClient.convertToType(data['website'], 'String');
            }
            if (data.hasOwnProperty('visibility')) {
                obj['visibility'] = Visibility.constructFromObject(data['visibility']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} groupname
 */
GroupUpdate.prototype['groupname'] = undefined;

/**
 * @member {String} email
 */
GroupUpdate.prototype['email'] = undefined;

/**
 * @member {String} description
 */
GroupUpdate.prototype['description'] = undefined;

/**
 * @member {String} organization
 */
GroupUpdate.prototype['organization'] = undefined;

/**
 * @member {String} location
 */
GroupUpdate.prototype['location'] = undefined;

/**
 * @member {String} website
 */
GroupUpdate.prototype['website'] = undefined;

/**
 * @member {module:model/Visibility} visibility
 */
GroupUpdate.prototype['visibility'] = undefined;






export default GroupUpdate;

