/**
 * ChronosDB swagger
 * ChronosDB time series database API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CollectionObj from './CollectionObj';
import ObjectType from './ObjectType';
import SpaceObj from './SpaceObj';
import TimeseriesObj from './TimeseriesObj';

/**
 * The ModelObject model module.
 * @module model/ModelObject
 * @version 0.1
 */
class ModelObject {
    /**
     * Constructs a new <code>ModelObject</code>.
     * @alias module:model/ModelObject
     * @param type {module:model/ObjectType} 
     * @param path {String} 
     * @param subobject {Boolean} 
     */
    constructor(type, path, subobject) { 
        
        ModelObject.initialize(this, type, path, subobject);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, path, subobject) { 
        obj['type'] = type;
        obj['path'] = path;
        obj['subobject'] = subobject;
    }

    /**
     * Constructs a <code>ModelObject</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModelObject} obj Optional instance to populate.
     * @return {module:model/ModelObject} The populated <code>ModelObject</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelObject();

            if (data.hasOwnProperty('space')) {
                obj['space'] = SpaceObj.constructFromObject(data['space']);
            }
            if (data.hasOwnProperty('collection')) {
                obj['collection'] = CollectionObj.constructFromObject(data['collection']);
            }
            if (data.hasOwnProperty('timeseries')) {
                obj['timeseries'] = TimeseriesObj.constructFromObject(data['timeseries']);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ObjectType.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
            if (data.hasOwnProperty('subobject')) {
                obj['subobject'] = ApiClient.convertToType(data['subobject'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/SpaceObj} space
 */
ModelObject.prototype['space'] = undefined;

/**
 * @member {module:model/CollectionObj} collection
 */
ModelObject.prototype['collection'] = undefined;

/**
 * @member {module:model/TimeseriesObj} timeseries
 */
ModelObject.prototype['timeseries'] = undefined;

/**
 * @member {module:model/ObjectType} type
 */
ModelObject.prototype['type'] = undefined;

/**
 * @member {String} path
 */
ModelObject.prototype['path'] = undefined;

/**
 * @member {Boolean} subobject
 */
ModelObject.prototype['subobject'] = undefined;






export default ModelObject;

