/**
 * ChronosDB swagger
 * ChronosDB time series database API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NewPassword model module.
 * @module model/NewPassword
 * @version 0.1
 */
class NewPassword {
    /**
     * Constructs a new <code>NewPassword</code>.
     * @alias module:model/NewPassword
     */
    constructor() { 
        
        NewPassword.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>NewPassword</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NewPassword} obj Optional instance to populate.
     * @return {module:model/NewPassword} The populated <code>NewPassword</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NewPassword();

            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Password
 * @member {String} password
 */
NewPassword.prototype['password'] = undefined;






export default NewPassword;

