/**
 * ChronosDB swagger
 * ChronosDB time series database API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Observation model module.
 * @module model/Observation
 * @version 0.1
 */
class Observation {
    /**
     * Constructs a new <code>Observation</code>.
     * @alias module:model/Observation
     */
    constructor() { 
        
        Observation.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Observation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Observation} obj Optional instance to populate.
     * @return {module:model/Observation} The populated <code>Observation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Observation();

            if (data.hasOwnProperty('index')) {
                obj['index'] = ApiClient.convertToType(data['index'], Object);
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], Object);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Object} index
 */
Observation.prototype['index'] = undefined;

/**
 * @member {Object} value
 */
Observation.prototype['value'] = undefined;

/**
 * @member {Number} status
 */
Observation.prototype['status'] = undefined;






export default Observation;

