/**
 * ChronosDB swagger
 * ChronosDB time series database API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Action from './Action';
import Effect from './Effect';
import ModelObject from './ModelObject';
import Subject from './Subject';

/**
 * The Policy model module.
 * @module model/Policy
 * @version 0.1
 */
class Policy {
    /**
     * Constructs a new <code>Policy</code>.
     * @alias module:model/Policy
     * @param subject {module:model/Subject} 
     * @param _object {module:model/ModelObject} 
     * @param action {module:model/Action} 
     * @param effect {module:model/Effect} 
     */
    constructor(subject, _object, action, effect) { 
        
        Policy.initialize(this, subject, _object, action, effect);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, subject, _object, action, effect) { 
        obj['subject'] = subject;
        obj['object'] = _object;
        obj['action'] = action;
        obj['effect'] = effect;
    }

    /**
     * Constructs a <code>Policy</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Policy} obj Optional instance to populate.
     * @return {module:model/Policy} The populated <code>Policy</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Policy();

            if (data.hasOwnProperty('subject')) {
                obj['subject'] = Subject.constructFromObject(data['subject']);
            }
            if (data.hasOwnProperty('object')) {
                obj['object'] = ModelObject.constructFromObject(data['object']);
            }
            if (data.hasOwnProperty('action')) {
                obj['action'] = Action.constructFromObject(data['action']);
            }
            if (data.hasOwnProperty('effect')) {
                obj['effect'] = Effect.constructFromObject(data['effect']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Subject} subject
 */
Policy.prototype['subject'] = undefined;

/**
 * @member {module:model/ModelObject} object
 */
Policy.prototype['object'] = undefined;

/**
 * @member {module:model/Action} action
 */
Policy.prototype['action'] = undefined;

/**
 * @member {module:model/Effect} effect
 */
Policy.prototype['effect'] = undefined;






export default Policy;

