/**
 * ChronosDB swagger
 * ChronosDB time series database API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ObjectType from './ObjectType';

/**
 * The PolicyUpdateObject model module.
 * @module model/PolicyUpdateObject
 * @version 0.1
 */
class PolicyUpdateObject {
    /**
     * Constructs a new <code>PolicyUpdateObject</code>.
     * @alias module:model/PolicyUpdateObject
     * @param type {module:model/ObjectType} 
     * @param subobject {Boolean} 
     */
    constructor(type, subobject) { 
        
        PolicyUpdateObject.initialize(this, type, subobject);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, subobject) { 
        obj['type'] = type;
        obj['subobject'] = subobject;
    }

    /**
     * Constructs a <code>PolicyUpdateObject</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PolicyUpdateObject} obj Optional instance to populate.
     * @return {module:model/PolicyUpdateObject} The populated <code>PolicyUpdateObject</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PolicyUpdateObject();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ObjectType.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('space_id')) {
                obj['space_id'] = ApiClient.convertToType(data['space_id'], 'String');
            }
            if (data.hasOwnProperty('coll_id')) {
                obj['coll_id'] = ApiClient.convertToType(data['coll_id'], 'String');
            }
            if (data.hasOwnProperty('tsid')) {
                obj['tsid'] = ApiClient.convertToType(data['tsid'], 'String');
            }
            if (data.hasOwnProperty('subobject')) {
                obj['subobject'] = ApiClient.convertToType(data['subobject'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ObjectType} type
 */
PolicyUpdateObject.prototype['type'] = undefined;

/**
 * @member {String} space_id
 */
PolicyUpdateObject.prototype['space_id'] = undefined;

/**
 * @member {String} coll_id
 */
PolicyUpdateObject.prototype['coll_id'] = undefined;

/**
 * @member {String} tsid
 */
PolicyUpdateObject.prototype['tsid'] = undefined;

/**
 * @member {Boolean} subobject
 */
PolicyUpdateObject.prototype['subobject'] = undefined;






export default PolicyUpdateObject;

