/**
 * ChronosDB swagger
 * ChronosDB time series database API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class SubjectType.
* @enum {}
* @readonly
*/
export default class SubjectType {
    
        /**
         * value: "u"
         * @const
         */
        "u" = "u";

    
        /**
         * value: "g"
         * @const
         */
        "g" = "g";

    

    /**
    * Returns a <code>SubjectType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/SubjectType} The enum <code>SubjectType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

