/**
 * ChronosDB swagger
 * ChronosDB time series database API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DType from './DType';
import Frequency from './Frequency';
import IType from './IType';
import TSI from './TSI';
import TimeSeriesCore from './TimeSeriesCore';
import TimeSeriesSummaryAllOf from './TimeSeriesSummaryAllOf';

/**
 * The TimeSeriesSummary model module.
 * @module model/TimeSeriesSummary
 * @version 0.1
 */
class TimeSeriesSummary {
    /**
     * Constructs a new <code>TimeSeriesSummary</code>.
     * returned when listing time series
     * @alias module:model/TimeSeriesSummary
     * @implements module:model/TimeSeriesCore
     * @implements module:model/TSI
     * @implements module:model/TimeSeriesSummaryAllOf
     */
    constructor() { 
        TimeSeriesCore.initialize(this);TSI.initialize(this);TimeSeriesSummaryAllOf.initialize(this);
        TimeSeriesSummary.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TimeSeriesSummary</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TimeSeriesSummary} obj Optional instance to populate.
     * @return {module:model/TimeSeriesSummary} The populated <code>TimeSeriesSummary</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TimeSeriesSummary();
            TimeSeriesCore.constructFromObject(data, obj);
            TSI.constructFromObject(data, obj);
            TimeSeriesSummaryAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('tsid')) {
                obj['tsid'] = ApiClient.convertToType(data['tsid'], 'String');
            }
            if (data.hasOwnProperty('collId')) {
                obj['collId'] = ApiClient.convertToType(data['collId'], 'String');
            }
            if (data.hasOwnProperty('dtype')) {
                obj['dtype'] = DType.constructFromObject(data['dtype']);
            }
            if (data.hasOwnProperty('dparams')) {
                obj['dparams'] = ApiClient.convertToType(data['dparams'], Object);
            }
            if (data.hasOwnProperty('itype')) {
                obj['itype'] = IType.constructFromObject(data['itype']);
            }
            if (data.hasOwnProperty('freq')) {
                obj['freq'] = Frequency.constructFromObject(data['freq']);
            }
            if (data.hasOwnProperty('fparams')) {
                obj['fparams'] = ApiClient.convertToType(data['fparams'], Object);
            }
            if (data.hasOwnProperty('entity')) {
                obj['entity'] = ApiClient.convertToType(data['entity'], 'Number');
            }
            if (data.hasOwnProperty('variable')) {
                obj['variable'] = ApiClient.convertToType(data['variable'], 'String');
            }
            if (data.hasOwnProperty('tsi')) {
                obj['tsi'] = ApiClient.convertToType(data['tsi'], 'String');
            }
            if (data.hasOwnProperty('space')) {
                obj['space'] = ApiClient.convertToType(data['space'], 'String');
            }
            if (data.hasOwnProperty('collection')) {
                obj['collection'] = ApiClient.convertToType(data['collection'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('discontinued')) {
                obj['discontinued'] = ApiClient.convertToType(data['discontinued'], 'Boolean');
            }
            if (data.hasOwnProperty('unit')) {
                obj['unit'] = ApiClient.convertToType(data['unit'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {String} tsid
 */
TimeSeriesSummary.prototype['tsid'] = undefined;

/**
 * @member {String} collId
 */
TimeSeriesSummary.prototype['collId'] = undefined;

/**
 * @member {module:model/DType} dtype
 */
TimeSeriesSummary.prototype['dtype'] = undefined;

/**
 * parameters of data type, e.g. enum
 * @member {Object} dparams
 */
TimeSeriesSummary.prototype['dparams'] = undefined;

/**
 * @member {module:model/IType} itype
 */
TimeSeriesSummary.prototype['itype'] = undefined;

/**
 * @member {module:model/Frequency} freq
 */
TimeSeriesSummary.prototype['freq'] = undefined;

/**
 * parameters of time index type, e.g. time zone if applicable, pivot date, etc
 * @member {Object} fparams
 */
TimeSeriesSummary.prototype['fparams'] = undefined;

/**
 * Entity is used in panel data to associate time series with a unit or individual, e.g. household or company, etc. It is used together with variable name to create a unique reference to time series in a panel collection, (entity, variable). Entity is immutable
 * @member {Number} entity
 */
TimeSeriesSummary.prototype['entity'] = undefined;

/**
 * variable is used in panel data to associate time series with a cross-sectional measure, e.g. eye color, etc. It is used together with variable name to create a unique reference to time series in a panel collection, (entity, variable). Variable is immutable
 * @member {String} variable
 */
TimeSeriesSummary.prototype['variable'] = undefined;

/**
 * Time Series Identifier as a string where ts name, collection name and space name as separated by comma
 * @member {String} tsi
 */
TimeSeriesSummary.prototype['tsi'] = undefined;

/**
 * @member {String} space
 */
TimeSeriesSummary.prototype['space'] = undefined;

/**
 * @member {String} collection
 */
TimeSeriesSummary.prototype['collection'] = undefined;

/**
 * unique series name in a collection
 * @member {String} name
 */
TimeSeriesSummary.prototype['name'] = undefined;

/**
 * Title of time series
 * @member {String} title
 */
TimeSeriesSummary.prototype['title'] = undefined;

/**
 * Time series, which are no longer recorded can be marked as discontinued. Discontinued series can be kept in the database for historical reasons
 * @member {Boolean} discontinued
 */
TimeSeriesSummary.prototype['discontinued'] = undefined;

/**
 * units of values
 * @member {Object} unit
 */
TimeSeriesSummary.prototype['unit'] = undefined;


// Implement TimeSeriesCore interface:
/**
 * @member {String} tsid
 */
TimeSeriesCore.prototype['tsid'] = undefined;
/**
 * @member {String} collId
 */
TimeSeriesCore.prototype['collId'] = undefined;
/**
 * @member {module:model/DType} dtype
 */
TimeSeriesCore.prototype['dtype'] = undefined;
/**
 * parameters of data type, e.g. enum
 * @member {Object} dparams
 */
TimeSeriesCore.prototype['dparams'] = undefined;
/**
 * @member {module:model/IType} itype
 */
TimeSeriesCore.prototype['itype'] = undefined;
/**
 * @member {module:model/Frequency} freq
 */
TimeSeriesCore.prototype['freq'] = undefined;
/**
 * parameters of time index type, e.g. time zone if applicable, pivot date, etc
 * @member {Object} fparams
 */
TimeSeriesCore.prototype['fparams'] = undefined;
/**
 * Entity is used in panel data to associate time series with a unit or individual, e.g. household or company, etc. It is used together with variable name to create a unique reference to time series in a panel collection, (entity, variable). Entity is immutable
 * @member {Number} entity
 */
TimeSeriesCore.prototype['entity'] = undefined;
/**
 * variable is used in panel data to associate time series with a cross-sectional measure, e.g. eye color, etc. It is used together with variable name to create a unique reference to time series in a panel collection, (entity, variable). Variable is immutable
 * @member {String} variable
 */
TimeSeriesCore.prototype['variable'] = undefined;
// Implement TSI interface:
/**
 * Time Series Identifier as a string where ts name, collection name and space name as separated by comma
 * @member {String} tsi
 */
TSI.prototype['tsi'] = undefined;
/**
 * @member {String} space
 */
TSI.prototype['space'] = undefined;
/**
 * @member {String} collection
 */
TSI.prototype['collection'] = undefined;
/**
 * unique series name in a collection
 * @member {String} name
 */
TSI.prototype['name'] = undefined;
// Implement TimeSeriesSummaryAllOf interface:
/**
 * Title of time series
 * @member {String} title
 */
TimeSeriesSummaryAllOf.prototype['title'] = undefined;
/**
 * Time series, which are no longer recorded can be marked as discontinued. Discontinued series can be kept in the database for historical reasons
 * @member {Boolean} discontinued
 */
TimeSeriesSummaryAllOf.prototype['discontinued'] = undefined;
/**
 * units of values
 * @member {Object} unit
 */
TimeSeriesSummaryAllOf.prototype['unit'] = undefined;




export default TimeSeriesSummary;

