/**
 * ChronosDB swagger
 * ChronosDB time series database API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DType from './DType';
import Frequency from './Frequency';
import IType from './IType';

/**
 * The TimeSeriesCore model module.
 * @module model/TimeSeriesCore
 * @version 0.1
 */
class TimeSeriesCore {
    /**
     * Constructs a new <code>TimeSeriesCore</code>.
     * Immutable part of time series definition
     * @alias module:model/TimeSeriesCore
     */
    constructor() { 
        
        TimeSeriesCore.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TimeSeriesCore</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TimeSeriesCore} obj Optional instance to populate.
     * @return {module:model/TimeSeriesCore} The populated <code>TimeSeriesCore</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TimeSeriesCore();

            if (data.hasOwnProperty('tsid')) {
                obj['tsid'] = ApiClient.convertToType(data['tsid'], 'String');
            }
            if (data.hasOwnProperty('collId')) {
                obj['collId'] = ApiClient.convertToType(data['collId'], 'String');
            }
            if (data.hasOwnProperty('dtype')) {
                obj['dtype'] = DType.constructFromObject(data['dtype']);
            }
            if (data.hasOwnProperty('dparams')) {
                obj['dparams'] = ApiClient.convertToType(data['dparams'], Object);
            }
            if (data.hasOwnProperty('itype')) {
                obj['itype'] = IType.constructFromObject(data['itype']);
            }
            if (data.hasOwnProperty('freq')) {
                obj['freq'] = Frequency.constructFromObject(data['freq']);
            }
            if (data.hasOwnProperty('fparams')) {
                obj['fparams'] = ApiClient.convertToType(data['fparams'], Object);
            }
            if (data.hasOwnProperty('entity')) {
                obj['entity'] = ApiClient.convertToType(data['entity'], 'Number');
            }
            if (data.hasOwnProperty('variable')) {
                obj['variable'] = ApiClient.convertToType(data['variable'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} tsid
 */
TimeSeriesCore.prototype['tsid'] = undefined;

/**
 * @member {String} collId
 */
TimeSeriesCore.prototype['collId'] = undefined;

/**
 * @member {module:model/DType} dtype
 */
TimeSeriesCore.prototype['dtype'] = undefined;

/**
 * parameters of data type, e.g. enum
 * @member {Object} dparams
 */
TimeSeriesCore.prototype['dparams'] = undefined;

/**
 * @member {module:model/IType} itype
 */
TimeSeriesCore.prototype['itype'] = undefined;

/**
 * @member {module:model/Frequency} freq
 */
TimeSeriesCore.prototype['freq'] = undefined;

/**
 * parameters of time index type, e.g. time zone if applicable, pivot date, etc
 * @member {Object} fparams
 */
TimeSeriesCore.prototype['fparams'] = undefined;

/**
 * Entity is used in panel data to associate time series with a unit or individual, e.g. household or company, etc. It is used together with variable name to create a unique reference to time series in a panel collection, (entity, variable). Entity is immutable
 * @member {Number} entity
 */
TimeSeriesCore.prototype['entity'] = undefined;

/**
 * variable is used in panel data to associate time series with a cross-sectional measure, e.g. eye color, etc. It is used together with variable name to create a unique reference to time series in a panel collection, (entity, variable). Variable is immutable
 * @member {String} variable
 */
TimeSeriesCore.prototype['variable'] = undefined;






export default TimeSeriesCore;

