/**
 * ChronosDB swagger
 * ChronosDB time series database API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserSummary model module.
 * @module model/UserSummary
 * @version 0.1
 */
class UserSummary {
    /**
     * Constructs a new <code>UserSummary</code>.
     * @alias module:model/UserSummary
     */
    constructor() { 
        
        UserSummary.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserSummary</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserSummary} obj Optional instance to populate.
     * @return {module:model/UserSummary} The populated <code>UserSummary</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserSummary();

            if (data.hasOwnProperty('uid')) {
                obj['uid'] = ApiClient.convertToType(data['uid'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} uid
 */
UserSummary.prototype['uid'] = undefined;

/**
 * @member {String} username
 */
UserSummary.prototype['username'] = undefined;

/**
 * @member {String} firstName
 */
UserSummary.prototype['firstName'] = undefined;

/**
 * @member {String} lastName
 */
UserSummary.prototype['lastName'] = undefined;

/**
 * @member {String} email
 */
UserSummary.prototype['email'] = undefined;






export default UserSummary;

