/**
 * ChronosDB swagger
 * ChronosDB time series database API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VintageSummary model module.
 * @module model/VintageSummary
 * @version 0.1
 */
class VintageSummary {
    /**
     * Constructs a new <code>VintageSummary</code>.
     * Vintage tag summary
     * @alias module:model/VintageSummary
     */
    constructor() { 
        
        VintageSummary.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VintageSummary</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VintageSummary} obj Optional instance to populate.
     * @return {module:model/VintageSummary} The populated <code>VintageSummary</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VintageSummary();

            if (data.hasOwnProperty('coll_id')) {
                obj['coll_id'] = ApiClient.convertToType(data['coll_id'], 'String');
            }
            if (data.hasOwnProperty('vid')) {
                obj['vid'] = ApiClient.convertToType(data['vid'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('realtime')) {
                obj['realtime'] = ApiClient.convertToType(data['realtime'], 'Date');
            }
            if (data.hasOwnProperty('realStart')) {
                obj['realStart'] = ApiClient.convertToType(data['realStart'], 'Date');
            }
            if (data.hasOwnProperty('realEnd')) {
                obj['realEnd'] = ApiClient.convertToType(data['realEnd'], 'Date');
            }
            if (data.hasOwnProperty('tsids')) {
                obj['tsids'] = ApiClient.convertToType(data['tsids'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} coll_id
 */
VintageSummary.prototype['coll_id'] = undefined;

/**
 * @member {String} vid
 */
VintageSummary.prototype['vid'] = undefined;

/**
 * @member {String} name
 */
VintageSummary.prototype['name'] = undefined;

/**
 * @member {String} description
 */
VintageSummary.prototype['description'] = undefined;

/**
 * @member {Date} realtime
 */
VintageSummary.prototype['realtime'] = undefined;

/**
 * @member {Date} realStart
 */
VintageSummary.prototype['realStart'] = undefined;

/**
 * @member {Date} realEnd
 */
VintageSummary.prototype['realEnd'] = undefined;

/**
 * array of time series id, which were saved in this vintage
 * @member {Array.<String>} tsids
 */
VintageSummary.prototype['tsids'] = undefined;






export default VintageSummary;

