/**
 * ChronosDB swagger
 * ChronosDB time series database API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: apiteam@chronosdb.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VintageUpdate model module.
 * @module model/VintageUpdate
 * @version 0.1
 */
class VintageUpdate {
    /**
     * Constructs a new <code>VintageUpdate</code>.
     * Vintage tag is a label associated with a real time (valid time) in a collection. 
     * @alias module:model/VintageUpdate
     */
    constructor() { 
        
        VintageUpdate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VintageUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VintageUpdate} obj Optional instance to populate.
     * @return {module:model/VintageUpdate} The populated <code>VintageUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VintageUpdate();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], {'String': Object});
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
VintageUpdate.prototype['name'] = undefined;

/**
 * @member {String} description
 */
VintageUpdate.prototype['description'] = undefined;

/**
 * @member {Object.<String, Object>} metadata
 */
VintageUpdate.prototype['metadata'] = undefined;






export default VintageUpdate;

