/**
 * FRED API
 * API for accessing economic data from the Federal Reserve Economic Data (FRED) database.
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ReleasesReleasesInner model module.
 * @module model/ReleasesReleasesInner
 * @version 1.0.2
 */
class ReleasesReleasesInner {
    /**
     * Constructs a new <code>ReleasesReleasesInner</code>.
     * @alias module:model/ReleasesReleasesInner
     */
    constructor() { 
        
        ReleasesReleasesInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ReleasesReleasesInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReleasesReleasesInner} obj Optional instance to populate.
     * @return {module:model/ReleasesReleasesInner} The populated <code>ReleasesReleasesInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReleasesReleasesInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('realtime_start')) {
                obj['realtime_start'] = ApiClient.convertToType(data['realtime_start'], 'Date');
            }
            if (data.hasOwnProperty('realtime_end')) {
                obj['realtime_end'] = ApiClient.convertToType(data['realtime_end'], 'Date');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('press_release')) {
                obj['press_release'] = ApiClient.convertToType(data['press_release'], 'Boolean');
            }
            if (data.hasOwnProperty('link')) {
                obj['link'] = ApiClient.convertToType(data['link'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ReleasesReleasesInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ReleasesReleasesInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['link'] && !(typeof data['link'] === 'string' || data['link'] instanceof String)) {
            throw new Error("Expected the field `link` to be a primitive type in the JSON string but got " + data['link']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
ReleasesReleasesInner.prototype['id'] = undefined;

/**
 * @member {Date} realtime_start
 */
ReleasesReleasesInner.prototype['realtime_start'] = undefined;

/**
 * @member {Date} realtime_end
 */
ReleasesReleasesInner.prototype['realtime_end'] = undefined;

/**
 * @member {String} name
 */
ReleasesReleasesInner.prototype['name'] = undefined;

/**
 * @member {Boolean} press_release
 */
ReleasesReleasesInner.prototype['press_release'] = undefined;

/**
 * @member {String} link
 */
ReleasesReleasesInner.prototype['link'] = undefined;






export default ReleasesReleasesInner;

